site_name: Andrew Clarke


  
theme:
  icon:
    repo: fontawesome/brands/github

  name: material

  font:
    text: Noto Sans
    code: Ubuntu

  features:
    - navigation.tabs
    - header.autohide
    - navigation.top

  palette:

    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode


markdown_extensions:
  - meta

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/apscandy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/andrew-clarke-534a62195/

repo_url: https://github.com/apscandy/resume
repo_name: apscandy/resume
