site_name: Andrew Clarke
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: Noto Sans
  features:
    - navigation.tabs
    - header.autohide
    - navigation.top
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - meta
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk
